export const logos = [
  {
    id: 1,
    url: "/assets/logos/HKTDC_Filmart_Logo-Purple-on-White-200x200-1 1.png",
  },
  { id: 2, url: "/assets/logos/HotDocs-Logo 1.png" },
  { id: 3, url: "/assets/logos/image 28.png" },
  { id: 4, url: "/assets/logos/image 29.png" },
  { id: 5, url: "/assets/logos/image 30.png" },
  { id: 6, url: "/assets/logos/image 31.png" },
  { id: 7, url: "/assets/logos/image 32.png" },
  { id: 8, url: "/assets/logos/image 33.png" },
  { id: 9, url: "/assets/logos/image 34.png" },
  { id: 10, url: "/assets/logos/image 35.png" },
  { id: 11, url: "/assets/logos/image 36.png" },
  { id: 12, url: "/assets/logos/image 37.png" },
  { id: 13, url: "/assets/logos/image 38.png" },
  { id: 14, url: "/assets/logos/image 39.png" },
  { id: 15, url: "/assets/logos/image 40.png" },
  { id: 16, url: "/assets/logos/image 41.png" },
  { id: 17, url: "/assets/logos/image 42.png" },
  { id: 18, url: "/assets/logos/image 43.png" },
  { id: 19, url: "/assets/logos/image 44.png" },
  { id: 20, url: "/assets/logos/image 45.png" },
  { id: 21, url: "/assets/logos/image 46.png" },
  { id: 22, url: "/assets/logos/image 47.png" },
  { id: 23, url: "/assets/logos/image 48.png" },
  { id: 24, url: "/assets/logos/image 49.png" },
  { id: 25, url: "/assets/logos/image 50.png" },
  { id: 26, url: "/assets/logos/image 51.png" },
  { id: 27, url: "/assets/logos/Marche-Du-Film-2022-200x200-1 1.png" },
  { id: 28, url: "/assets/logos/MIFF-Logo-200x200-1 1.png" },
  { id: 29, url: "/assets/logos/MIP-cancun-Logo 1.png" },
  { id: 30, url: "/assets/logos/MIP-com-Logo-1 1.png" },
  { id: 31, url: "/assets/logos/MIP-DOC-Logo 1.png" },
  { id: 32, url: "/assets/logos/MIP-TV-Logo 1.png" },
  { id: 33, url: "/assets/logos/Natpe-Logo 1.png" },
  { id: 34, url: "/assets/logos/NATPE-Streaming-Logo-200x200-1 1.png" },
  { id: 35, url: "/assets/logos/OTtx-logo-200x200-sm 1.png" },
  { id: 36, url: "/assets/logos/Sundance-Logo 1.png" },
  { id: 37, url: "/assets/logos/TIFF-Logo 1.png" },
  { id: 38, url: "/assets/logos/Ventana-Sur-logo 1.png" },
];
