export const globalReleasePartners = [
  [
    { id: "1", title: "PixelWorks", image: "/assets/logos/image1.png" },
    { id: "2", title: "FrameForge", image: "/assets/logos/image2.png" },
    { id: "3", title: "VisionCraft", image: "/assets/logos/image3.png" },
    null,
    { id: "4", title: "CineMaster", image: "/assets/logos/image4.png" },
    null,
    { id: "5", title: "StoryGrid", image: "/assets/logos/image5.png" },
    { id: "6", title: "FilmScope", image: "/assets/logos/image6.png" },
  ],
  [
    null,
    { id: "7", title: "MediaNest", image: "/assets/logos/image7.png" },
    { id: "8", title: "ReelEdge", image: "/assets/logos/image8.png" },
    null,
    { id: "9", title: "ArtSphere", image: "/assets/logos/image9.png" },
    { id: "10", title: "SceneSync", image: "/assets/logos/image10.png" },
    { id: "11", title: "ClipStream", image: "/assets/logos/image11.png" },
    null,
  ],
  [
    { id: "12", title: "Broadcastly", image: "/assets/logos/image12.png" },
    { id: "13", title: "FlickWave", image: "/assets/logos/image13.png" },
    null,
    { id: "14", title: "ReelUnion", image: "/assets/logos/image14.png" },
    { id: "15", title: "EditNest", image: "/assets/logos/image15.png" },
    null,
    { id: "16", title: "FrameCircle", image: "/assets/logos/image16.png" },
    { id: "17", title: "StudioDrop", image: "/assets/logos/image17.png" },
  ],
  [
    null,
    { id: "18", title: "Lightbox Media", image: "/assets/logos/image18.png" },
    { id: "19", title: "StreamCast", image: "/assets/logos/image19.png" },
    { id: "20", title: "VisionSquare", image: "/assets/logos/image20.png" },
    null,
    null,
    { id: "21", title: "CinePilot", image: "/assets/logos/image21.png" },
  ],
];

export const marketAttendace = [
  [
    { id: "22", title: "DocuWorld", image: "/assets/logos/image22.png" },
    null,
    { id: "23", title: "MetaView", image: "/assets/logos/image23.png" },
    { id: "24", title: "SpotFrame", image: "/assets/logos/image24.png" },
    { id: "25", title: "BrightTape", image: "/assets/logos/image25.png" },
    null,
    { id: "26", title: "ReelStory", image: "/assets/logos/image26.png" },
    { id: "27", title: "FastTrack TV", image: "/assets/logos/image27.png" },
  ],
  [
    null,
    { id: "28", title: "NovaVision", image: "/assets/logos/image28.png" },
    null,
    { id: "29", title: "StreamLab", image: "/assets/logos/image29.png" },
    { id: "30", title: "SkyCast", image: "/assets/logos/image30.png" },
    { id: "31", title: "EchoFrame", image: "/assets/logos/image31.png" },
    null,
    { id: "32", title: "AltScreen", image: "/assets/logos/image32.png" },
  ],
  [
    { id: "33", title: "CineBridge", image: "/assets/logos/image33.png" },
    { id: "34", title: "FilmSprint", image: "/assets/logos/image34.png" },
    { id: "35", title: "VisionBeat", image: "/assets/logos/image35.png" },
    { id: "36", title: "ClipNation", image: "/assets/logos/image36.png" },
    null,
    null,
    { id: "37", title: "StudioNova", image: "/assets/logos/image37.png" },
    { id: "38", title: "FlickTower", image: "/assets/logos/image38.png" },
  ],
];
