import type { Metadata } from "next";

import MainLayout from "@/components/layout/main-layout";

import "@/styles/globals.scss";
import { UIContextProvider } from "@/context/ui-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UIContextProvider>
      <MainLayout>{children}</MainLayout>
    </UIContextProvider>
  );
}
